// Code originally generated by Claude-3 AI March 2024
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {NgForOf, NgIf} from "@angular/common";
import {FormsModule} from "@angular/forms";
import { environment } from '@environments/environment';

interface Book {
  title: string;
  rating: number;
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  standalone: true,
  imports: [
    NgForOf,
    FormsModule,
    NgIf
  ],
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Book Review';
  books: Book[] = [

  ];
  newBook = {
    title: '',
    rating: 0
  };



  constructor(private http: HttpClient) {
    this.fetchBooks();
  }

  fetchBooks() {
    const baseUrl = environment.serverUrl;
    this.http.get<Book[]>(`${baseUrl}/books`).subscribe(
       (data) => {
         this.books = data;
       },
       (error) => {
         console.error('Error fetching books:', error); // Log the error object
         console.log('Error Details:', error.message, error.status); // Extra info
       }
     );
  }

  onSubmit() {
    const baseUrl = environment.serverUrl;
    this.http.post<Book>(`${baseUrl}/books`, this.newBook).subscribe(
      () => {
        // Reset form input fields
        this.newBook.title = '';
        this.newBook.rating = 0;

        // Update the books array (consider efficient updates)
        this.fetchBooks();
      },
      (error) => {
        console.error('Error adding book:', error);
      }
    );
  }
}
